import type { Contact, Message, Prospect, Thread } from "./types";

export const contacts: Contact[] = [
  {
    id: "c1",
    name: "Hendra Wijaya",
    company: "Java Forwarding Co.",
    role: "Operations Manager",
    country: "Indonesia",
    avatarInitials: "HW",
    identities: [
      { channel: "whatsapp", handle: "+62 812-3456-7890" },
      { channel: "email", handle: "hendra@javaforwarding.co.id" },
    ],
  },
  {
    id: "c2",
    name: "Marta Schulz",
    company: "Nordholz Import GmbH",
    role: "Procurement Lead",
    country: "Jerman",
    avatarInitials: "MS",
    identities: [
      { channel: "email", handle: "m.schulz@nordholz-import.de" },
      { channel: "linkedin", handle: "linkedin.com/in/martaschulz" },
    ],
  },
  {
    id: "c3",
    name: "Kenji Sato",
    company: "Sato Trading K.K.",
    role: "Buyer, Furniture Division",
    country: "Jepang",
    avatarInitials: "KS",
    identities: [
      { channel: "whatsapp", handle: "+81 90-1234-5678" },
      { channel: "linkedin", handle: "linkedin.com/in/kenjisato" },
    ],
  },
  {
    id: "c4",
    name: "Amara Okafor",
    company: "Lagos Freight Partners",
    role: "Forwarder Agent",
    country: "Nigeria",
    avatarInitials: "AO",
    identities: [{ channel: "email", handle: "amara@lagosfreight.com" }],
  },
];

export const threads: Thread[] = [
  {
    id: "t1",
    contact: contacts[0],
    shipmentRef: "SHP-2026-0417",
    lastMessagePreview: "B/L draft sudah saya kirim, mohon dicek sebelum kontainer masuk pelabuhan.",
    lastMessageAt: "09:42",
    unreadCount: 2,
    channelsInThread: ["whatsapp", "email"],
  },
  {
    id: "t2",
    contact: contacts[1],
    shipmentRef: "SHP-2026-0409",
    lastMessagePreview: "Invoice line item untuk handling charge belum sesuai kesepakatan awal.",
    lastMessageAt: "Kemarin",
    unreadCount: 1,
    channelsInThread: ["email", "linkedin"],
  },
  {
    id: "t3",
    contact: contacts[2],
    lastMessagePreview: "Terima kasih atas sample rotannya, kami tertarik lanjut ke MOQ.",
    lastMessageAt: "Kemarin",
    unreadCount: 0,
    channelsInThread: ["whatsapp"],
  },
  {
    id: "t4",
    contact: contacts[3],
    shipmentRef: "SHP-2026-0421",
    lastMessagePreview: "Kapal reschedule ke Kamis, saya update dokumen booking-nya.",
    lastMessageAt: "Sen",
    unreadCount: 0,
    channelsInThread: ["email"],
  },
];

export const messagesByThread: Record<string, Message[]> = {
  t1: [
    {
      id: "m1",
      threadId: "t1",
      channel: "email",
      direction: "inbound",
      author: "Hendra Wijaya",
      body: "Pagi, packing list final untuk SHP-2026-0417 sudah bisa diambil. 3 kontainer 40ft.",
      timestamp: "08:10",
      deliveryStatus: "read",
    },
    {
      id: "m2",
      threadId: "t1",
      channel: "whatsapp",
      direction: "outbound",
      author: "Anda",
      body: "Siap Pak Hendra, kami siapkan draft invoice berdasarkan packing list ini dulu ya.",
      timestamp: "08:22",
      deliveryStatus: "read",
    },
    {
      id: "m3",
      threadId: "t1",
      channel: "whatsapp",
      direction: "inbound",
      author: "Hendra Wijaya",
      body: "B/L draft sudah saya kirim, mohon dicek sebelum kontainer masuk pelabuhan.",
      timestamp: "09:42",
      deliveryStatus: "delivered",
    },
  ],
  t2: [
    {
      id: "m4",
      threadId: "t2",
      channel: "linkedin",
      direction: "inbound",
      author: "Marta Schulz",
      body: "Hi, terhubung setelah trade show Hannover minggu lalu.",
      timestamp: "Sel",
      deliveryStatus: "read",
    },
    {
      id: "m5",
      threadId: "t2",
      channel: "email",
      direction: "inbound",
      author: "Marta Schulz",
      body: "Invoice line item untuk handling charge belum sesuai kesepakatan awal, bisa dijelaskan rinciannya?",
      timestamp: "Kemarin",
      deliveryStatus: "read",
    },
  ],
  t3: [
    {
      id: "m6",
      threadId: "t3",
      channel: "whatsapp",
      direction: "inbound",
      author: "Kenji Sato",
      body: "Terima kasih atas sample rotannya, kami tertarik lanjut ke MOQ.",
      timestamp: "Kemarin",
      deliveryStatus: "read",
    },
  ],
  t4: [
    {
      id: "m7",
      threadId: "t4",
      channel: "email",
      direction: "inbound",
      author: "Amara Okafor",
      body: "Kapal reschedule ke Kamis, saya update dokumen booking-nya.",
      timestamp: "Sen",
      deliveryStatus: "read",
    },
  ],
};

export const sampleProspects: Prospect[] = [
  {
    id: "p1",
    name: "Lukas Berger",
    company: "Berger Wohnkultur GmbH",
    role: "Head of Sourcing",
    country: "Jerman",
    commodity: "Furnitur rotan & anyaman",
    matchScore: 92,
    source: "linkedin",
    sourceUrl: "linkedin.com/in/lukasberger",
    summary: "Aktif posting soal sourcing furnitur outdoor Asia Tenggara 6 minggu terakhir.",
  },
  {
    id: "p2",
    name: "Elena Rossi",
    company: "Casa Bella Import",
    role: "Buyer",
    country: "Italia",
    commodity: "Furnitur rotan",
    matchScore: 87,
    source: "trade-directory",
    summary: "Terdaftar di direktori importir furnitur Uni Eropa, volume impor tahunan menengah.",
  },
  {
    id: "p3",
    name: "Willem de Vries",
    company: "Rotan & Co Rotterdam",
    role: "Purchasing Director",
    country: "Belanda",
    commodity: "Furnitur rotan & bambu",
    matchScore: 81,
    source: "email-signature",
    summary: "Ditemukan dari signature email di thread lama dengan forwarder Anda.",
  },
];
